sonar.projectKey=pop-quizz_pop-quizz-linux-front-end
sonar.organization=pop-quizz

sonar.sources=src
sonar.tests=tests

sonar.test.inclusions=**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
 